# Generated by Django 5.2.3 on 2025-06-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="crews",
            field=models.ManyToManyField(related_name="flights", to="airport.crew"),
        ),
    ]
