# Generated by Django 5.2.3 on 2025-07-06 19:09

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0004_airplane_image_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airplane",
            name="image",
            field=models.ImageField(
                null=True, upload_to=airport.models.airplane_image_path
            ),
        ),
    ]
